### ISSUE TITLE
pull document list down to refresh

### ISSUE THREAD

**Issue by jancborchardt** [litewrite/litewrite#121]
Pull to refresh is now a common pattern for refreshing data. We should use it for the document list – when you scroll it up (or pull it down), it should show a refresh indicator and trigger a remotestorage sync.

There are JS libraries for pull to refresh, but they all only work with touch, none of them works with mouse scrolling, which is a bit of a bummer.

**Comment by jorinvo** [comment]
Let's keep it simple. We don't need to add more interactions than necessary.
