### ISSUE TITLE
feedback about syncing in docs list

### ISSUE THREAD

**Issue by jancborchardt** [litewrite/litewrite#131]
When you connect your remoteStorage, it takes some time for the documents to roll in. In addition to the feedback the remoteStorage widget gives, it might be cool to have an additional spinner in the document list, where the documents then appear. We could use the same remoteStorage spinning icon as used in the widget, maybe half-transparent.

This is similar to #121 as for having remoteStorage widget functions directly in the app, but I think that’s very useful. It’s more contextual and where you would have it in an app which doesn’t use remoteStorage.

**Comment by jorinvo** [comment]
Not really necessary. If someone comes up with a nice implementation, I would be happy to merge a PR. Closing the issue for now.
