### ISSUE TITLE
delete functionallity including undo

### ISSUE THREAD

**Issue by jorinvo** [litewrite/litewrite#179]
especially on mobile it's quiet difficult to delete a document. 
maybe we can do it the iOS way where you swipe over the item in the list and then der appears a delete button.
on desktop we could just show a delete button when hovering an item in the documents list next to the item.

undo is something that could be implemented later.

**Comment by jorinvo** [comment]
Little note: This should also delete the shared document (or ask if it should be deleted).

**Comment by phylophyl** [comment]
It seems impossible to delete à note, did i miss something?

**Comment by skddc** [comment]
@phylophyl Removing all content from a note will delete it.

**Comment by phylophyl** [comment]
@skddc thank you! The answer should be added to the welcome text on litewrite

**Comment by raucao** [comment]
It's still pretty much impossible to delete docs on mobile. I'm not sure where that button could go tho. Maybe @jancborchardt has an idea?

**Comment by jancborchardt** [comment]
To not have a destructive action like that so presently, we could put it next to the word count on the bottom.

**Comment by jorinvo** [comment]
I can add a simple delete button next the the share button. We don't have a word count, think you meant the date. But that's not visible on mobile.
Simplest solution is to use the browser's `confirm()` and not implement any undo logic for now.

**Comment by raucao** [comment]
Perfect. Thanks!
