### ISSUE TITLE
public sharing & publishing

### ISSUE THREAD

**Issue by jancborchardt** [litewrite/litewrite#19]
With remoteStorage support (#7), we can add the ability to publicly share an article. This would make the article show up at litewrite.net/#user@provider.com/article (also see #17 about the document address).

Litewrite can then also be used as a publishing tool. If you hardcode your user address in, you could set it up on your personal server and publish articles at yourwebsite.com/#article

**Comment by jorinvo** [comment]
Closing this in favor of #230.

Regarding the (old) discussion here:
I'll add "share", "open" and "unshare" buttons.
And the shared note will be updated automatically.

Let's try this first and discuss further options later.
