### ISSUE TITLE
Can't connect to remoteStorage when installed as Amazon Web App

### ISSUE THREAD

**Issue by galfert** [litewrite/litewrite#195]
I installed Litewrite on Android from the Amazon App Store. I can't connect to my remoteStorage account.

I thinks it's a general remoteStorage.js problem, that's why I created an issue with more details at remotestorage/remotestorage.js/issues/444.

**Comment by jorinvo** [comment]
Let's close this for now.
A lot might have changed in between.
I created a new ticket to check the different platforms #227.

**Comment by skddc** [comment]
Seems like Amazon fixed this: https://github.com/remotestorage/remotestorage.js/issues/444#issuecomment-150832146
