### ISSUE TITLE
App breaks in Safari

### ISSUE THREAD

**Issue by skddc** [litewrite/litewrite#197]
I just tried out Litewrite on Safari (ML, 6.1), and after first connecting the storage, when I close the window and go back to Litewrite, I cannot select any note from the list anymore. (It'll also leave the "write" placeholder behind the text of the first, automatically selected note).

**Comment by jorinvo** [comment]
Let's close this for now.
A lot might have changed in between.
I created a new ticket to check the different platforms #227.
