### ISSUE TITLE
Litewrite.net does not work with 5apps' remote storage

### ISSUE THREAD

**Issue by nicatronTg** [litewrite/litewrite#200]
I'm guessing this is a case of the production environment being out of sync with the development version. Attempting to connect Litewrite to 5apps using OAuth results in a white page on the redirect back from 5apps, and no connection being made.

http://litewrite.github.io/litewrite/ works fine.

**Comment by jorinvo** [comment]
Let's close this for now.
A lot might have changed in between.
We'll test the new releases with 5apps for sure.
