### ISSUE TITLE
UX for creating notes and search

### ISSUE THREAD

**Issue by skddc** [litewrite/litewrite#201]
I just want to report something that is a bit annoying to me, because my brain doesn't seem to learn how to deal with this change at all: since the search field was added to the top of the sidebar, every single time I want to create a new note, I write the title of the note in that search field instead of clicking the small plus sign below it.

It happens to me literally every single time, and on the other hand I basically never need search. I'm not sure how many users want search for their notes front and center, but it might be worth looking into it and improving the UX there, either by moving the whole search field to another location, or improving the adding of notes somehow (not sure how exactly, just reporting what the UI does to my brain).

**Comment by jorinvo** [comment]
I also mention here, that I would be good if search is always accessible to be more consistent and not confuse users that want to try the search when they read about it (As discussed with @vovkkk in https://github.com/litewrite/litewrite/issues/227#issuecomment-167577329)
