### ISSUE TITLE
Chromium says: »remoteStorage not supported (private browsing mode?)«

### ISSUE THREAD

**Issue by jancborchardt** [litewrite/litewrite#205]
When opening Litewrite in Chromium, it says »remoteStorage not supported (private browsing mode?)«.

For [Sharedy](https://sharedy.5apps.com/) this doesn’t happen – maybe a regression in remoteStorage?

Any idea @michielbdejong @jorin-vogel?

**Comment by jorinvo** [comment]
Let's close this for now.
Was probably related to remotestorage anyways.
See #227 for further testing.
