### ISSUE TITLE
App for Ubuntu

### ISSUE THREAD

**Issue by 3arn0wl** [litewrite/litewrite#214]
Hi

I've been trying the Ubuntu Touch emulator, and noticed that there's a Litewrite app there.  I was just wondering if there's a similar build for the desktop?  I'm using nvpy at the moment, which is great,  but if I can choose where notes are synced, that would be better still.  (It's not at all obvious how choosing syncing destinations is done by the way, for non-techies, like me!)

**Comment by jorinvo** [comment]
I close this for now but I included Ubuntu Touch in the list of platforms we need to check (#277).
