### ISSUE TITLE
Litewrite a possible client web to Infinote protocol aka "Gobby"

### ISSUE THREAD

**Issue by valessiobrito** [litewrite/litewrite#216]
Suggest implementing the infinote protocol [0], which would make it  compatible with kobby[1] and gobby[2]. 

[0] https://github.com/gobby/gobby/wiki/API-Documentation
[1] http://kobby.greghaynes.net/
[2] https://github.com/gobby/gobby

**Comment by jorinvo** [comment]
I plan to reorganize Litewrite in a way so you can easily create a version with a custom syncing mechanism and create versions with different backends.

But in the moment this integration might be difficult.

Are you still working on the project?
jinfinote looks like it hasn't been updated for a while.

Thank you for the suggestion anyways!
We might look into it again in the future!
