### ISSUE TITLE
Encrypted notes

### ISSUE THREAD

**Issue by Ferk** [litewrite/litewrite#218]
While this tool is extremely useful for sharing notes across devices, allowing you to access your same notes at work, at home or in your phone, I'm very wary about using it for sensitive information, since the more places you use it in, the more careful you have to be.

Client-side password protection of the notes would be an awesome feature. And it would allow this tool to be used to safely keep notes about passwords, PINs and other info that could be accessed even on the move with a phone, as long as you remember your "master" password to decrypt the note.

This could be done optionally, without cluttering too much the interface.. perhaps replace the "+" button with two icons, one to create encrypted notes and another one for plain text notes. Then have an encrypted note icon to indicate the notes that use encryption in the list.

On creation of an encrypted note a password would be asked to the user. The password will be asked again every time he opens the encrypted note, and no unencrypted data will be kept in local storage. Perhaps also after a few minutes of inactivity clear the editor and ask again (in case you forget your tab open). The encryption could be symmetrical, just some AES using the hash of the provided password as the key.

**Comment by jorinvo** [comment]
Making encryption really secure is a really challenging task.

If you open your notes on any machine you have to trust the browser, its plugins and the OS.
It wouldn't be a good idea to load all your passwords in some browser.
Better keep them somewhere not connected to the web at all.

But if someone would like to try adding such a feature and finds a way to make it reasonable secure, I would curious to find out more.

I don't see myself experienced enough with security for this.

Your PR is welcome :wink:

**Comment by jancborchardt** [comment]
For encryption, I can recommend using https://laverna.cc instead – that’s also open source. As @jorinvo said encryption is really challenging, and it’s not really our focus with Litewrite.

**Comment by devurandom** [comment]
> For encryption, I can recommend using https://laverna.cc instead – that’s also open source. As @jorinvo said encryption is really challenging, and it’s not really our focus with Litewrite.

Laverna is not being actively developed anymore and it does not come with an easy way to share documents among multiple people (you can share the Laverna settings file, the encryption password and the remoteStorage account username and password, but that feels extremely cumbersome).
