### ISSUE TITLE
Self signed ssl certificate ?

### ISSUE THREAD

**Issue by khertan** [litewrite/litewrite#219]
Hi,
I m currently trying to use litewrite with my own server (reStore) on a raspberrypi. While i can t connect on App from Firefox Market place on bb10 z10 nor on desktop app installed under Gnome 3.14 from Firefox with Marketplace.

I didnt got any problem from the website (http://litewrite.net/) if i accept the unsecure self signed warning from Firefox.

Did you have any idea on how i can add my own certificate to the app ? or accept a self signed one ?

**Comment by jorinvo** [comment]
Sorry for the late response @khertan!

Thank you for pointing out about the missing certificate at https://litewrite.net/ (#228)!

If you want to host your own version, you need to provider your own certificate though...
But appart from that, it's just static files and you can host them like any other website.

Regarding the Marketplaces, we'll track this in issue #227.

**Comment by khertan** [comment]
Hi,

Main problem was using self signed certificate on Android. That's a pain.
Which should be easy to resolve soon with letsencrypt.org.

Thanks for your answer :)
