### ISSUE TITLE
FFOS version doesn't work off line

### ISSUE THREAD

**Issue by mniemann** [litewrite/litewrite#222]
I'm using Litewrite on a Flame phone running FireFix OS 2.2. I was camping and wanted to write a note and was told that the app requires an internet connection. But the Readme file states that it works offline.
Is there something I'm doing wrong? I did signup for remote storage.

**Comment by jancborchardt** [comment]
@mniemann just to be sure – you did install _and_ use the app before you went out camping, right? Then it should normally work.

**Comment by jorinvo** [comment]
The way @jancborchardt already described _should_ work.
Anyways, we'll do more testing in the new future - including Firefox OS and offline usage.
See #227.
