### ISSUE TITLE
Store data in local filesystem

### ISSUE THREAD

**Issue by jniggemann** [litewrite/litewrite#224]
litewrite looks cool, but I don't want my data to be stored "in the cloud".
I realize I could setup a RemoteStorage server, but that's one more component I'd have to maintain.

It would be very cool if litewrite could just save to the local filesystem the server is running on (or to a database, be it remote or local).

**Comment by jancborchardt** [comment]
It already does – it saves all notes to the local storage of your browser. :)

**Comment by jniggemann** [comment]
Yeah, but like many of us, I use multiple browsers on multiple machines...

**Comment by jniggemann** [comment]
OK, my bad. I didn't fully read the "This is an unhosted web app".part...

**Comment by jancborchardt** [comment]
@jniggemann you can also simply sign up for a https://5apps.com account – then go to Storage in the switcher on the top left and join the storage beta. Voila, you have remoteStorage :)
