### ISSUE TITLE
Check platforms

### ISSUE THREAD

**Issue by jorinvo** [litewrite/litewrite#227]
- [ ] Firefox
- [ ] Chrome
- [ ] Android
- [ ] IPhone
- [ ] IPad
- [ ] Chrome App Store
- [ ] Amazon Store
- [ ] Firefox Marketplace
- [ ] Firefox OS
- [ ] Internet Explorer 9
- [ ] Internet Explorer 10
- [ ] Internet Explorer 11
- [ ] Edge
- [ ] Windows Phone
- [ ] Chromium
- [ ] Safari Desktop
- [ ] Opera
- [ ] Ubuntu Touch

For each platform:
- Test in private mode
- Test offline version
- Update all the registered apps

**Comment by jorinvo** [comment]
What about the indie app store @jancborchardt ? Is this this one: http://indiewebcamp.com/store ?

**Comment by jancborchardt** [comment]
@jorinvo yeah, that effort has stalled however. We can revisit it when it progresses again and is recognized more widely.

**Comment by jorinvo** [comment]
@jancborchardt do you think we should keep Firefox OS?

**Comment by jorinvo** [comment]
I think the current version on [gh-pages](https://litewrite.github.io/litewrite/) is pretty close to what I would like to put on http://litewrite.net/ soon.
Everyone is welcome to give it a try on their favorite platform!
Please let me know about any issues you can find. 
All urgent issues are marked as [priority](https://github.com/litewrite/litewrite/labels/priority) (currently 3 small ones left).

cc @jancborchardt, @nilclass, @skddc, @3demax, @khertan, @galfert, @JohnTroony, @vovkkk, @krrrcks, @Vinnl, @fkooman

**Comment by JohnTroony** [comment]
Cool! Testing for Firefox and Chromium (on Arch-Linux)...

**Comment by vovkkk** [comment]
Fx 43.0.2, Windows 8.1

* The low part of each line is hidden (look at p and g in AppCache and Storage)  

    ![2015-12-28 04-38-05 litewrite - mozilla firefox](https://cloud.githubusercontent.com/assets/1975298/12012411/c0333af8-ad1c-11e5-8324-e076dfb916db.png)

* It says that <kbd>Alt+i</kbd> puts cursor in search field, but nothing happens and I don’t see search field at all anywhere.
    However, search field appear if there are about 9 notes, but <kbd>Alt+i</kbd> doesn’t work.

* Share doesn’t do anything, no even errors in console.

* Burger icon (while window is narrow) doesn’t stick on top of viewport, so I have to scroll up, imho, it is inconvenient.

Windows Phone 8.1

* Cursor is not visible.

* Swipe on note to show notes list brings up keyboard.

**Comment by jorinvo** [comment]
@vovkkk thank you for the help! 
Would be nice if you can help us even further to fix these issues:

1. I can't reproduce this issue in Firefox on Linux (with Russian document). Might this be related to Windows? Could you try if you get the same issue with Chrome? Or if you can also reproduce it on a different OS? Or maybe if it helps if we change the font used for Russian? Do you also have issues in a not-russian document?
2.1. The shortcut is `Alt+j`. I remember we chose this because we didn't want it to conflict with any built-in commands. If you have a better suggestion, would be happy to change it. 
2.2. Search is disabled as long as all notes fit on the screen. We probably should remove that. As soon as we find a less obtrusive way to show the search.
4. Our thinking was that we want to keep the UI as empty as possible. If you don't want to scroll all the way up, you could use the "swipe from left to right". We should probably mention this in the welcome document as well.
5. & 6. I'm not sure if I can support Windows Phone myself. I would be really happy to get some PRs for support though ...

**Comment by vovkkk** [comment]
The problem with font file

* Web font:

    ![2015-12-28 19-14-03 litewrite - mozilla firefox](https://cloud.githubusercontent.com/assets/1975298/12019190/531200c8-ad97-11e5-864e-3136a5041c8f.png)

* Installed font from http://gregorfont.com/fonts/Gregor.otf

    ![2015-12-28 19-13-13 litewrite - mozilla firefox](https://cloud.githubusercontent.com/assets/1975298/12019206/8f63528e-ad97-11e5-9895-84b1781adbc8.png)

    I’ve set `gfx.downloadable_fonts.enabled;false` in <about:config> to use system one.

* Chromium works right anyway

    ![2015-12-28 17-26-00 litewrite chromium](https://cloud.githubusercontent.com/assets/1975298/12019274/3d83f102-ad98-11e5-9036-581b4e0b80a7.png)


> Search is disabled as long as all notes fit on the screen. We probably should remove that. As soon as we find a less obtrusive way to show the search.

I’d suggest to show search if user hits <kbd>Alt+j</kbd> anyway.



> "swipe from left to right"

I see. BTW, attempt to highlight text with mouse may trigger swipe I just noticed.

**Comment by jorinvo** [comment]
I close this for now.
