### ISSUE TITLE
SSL for litewrite.net

### ISSUE THREAD

**Issue by jorinvo** [litewrite/litewrite#228]
Since this is all about privacy and freedom, litewrite should be available via HTTPS.
Is this possible with 5apps hosting @skddc? 
The domain comes from gandi and should have a SSL certificate (cc @jancborchardt).

**Comment by skddc** [comment]
Yes, it is.

**Comment by jorinvo** [comment]
@skddc any idea why it's not working right now?
If I try to go to https://litewrite.net/ I end up at https://5apps.tenderapp.com/ :confused:

**Comment by skddc** [comment]
Did you set it up for the app?

We can't do TLS/HTTPS automatically yet, because Let's Encrypt is not yet public.

**Comment by jorinvo** [comment]
Hm, @jancborchardt owns the domain. Have to ask him. 
But I guess he has to enable it at gandi.
Don't even know if we have cert there. It's only free for the first year. After it's something like 12€ / year.
Otherwise can also do [startssl](https://www.startssl.com/). Than should work with 5apps right?

**Comment by skddc** [comment]
We can make an exception, but usually we don't set up custom certificates. HTTPS on 5apps is usually a managed full-service option, incl. the certificate. Until we can do it automatically and for free via letsencrypt that is.

**Comment by jorinvo** [comment]
I would also be ok to pay for 5apps. However, I don't own the domain.
Can still switch to letsencrypt when it's available right?

**Comment by skddc** [comment]
As long as the domain is pointed to 5apps, we can validate the certificate.

Let's Encrypt should launch rather soon though, so not sure if it still makes sense. If anything, send us a cert and we'll set it up for free.

**Comment by jorinvo** [comment]
Thank you so much! I would also totally be willing to pay for it!

However, I also think that for an open source project it' fine to wait for letsencrypt..

**Comment by jorinvo** [comment]
letsencrypt is in public beta now.
https://letsencrypt.org/2015/12/03/entering-public-beta.html

**Comment by jancborchardt** [comment]
Let me know if I need to do anything with the domain at Gandi. :)

**Comment by skddc** [comment]
> letsencrypt is in public beta now.

We're following closely and will go live with our integration as soon as it's working and tested properly.

**Comment by jorinvo** [comment]
@skddc you added letsencrypt HTTPS to 5apps?!? 
It's awesome! This fixes this issue I guess :) Thanks!

**Comment by skddc** [comment]
Ohai. I forgot to update this issue after we added the cert for litewrite.net. :)
