### ISSUE TITLE
Issue with autosize

### ISSUE THREAD

**Issue by jorinvo** [litewrite/litewrite#232]
We should check if we can replace, or even need [autosize](https://github.com/jackmoore/autosize).
There are issues on desktop and mobile where the textarea doesn't fill the screen and is not scrollable.

cc @Vinnl, @jancborchardt

**Comment by jancborchardt** [comment]
Yeah, actually we probably don’t need autosize in the first place. Because it’s styled for the full screen anyway.

**Comment by jorinvo** [comment]
@jancborchardt maybe we have to digg in and find out why we put autosize in there in the first place...
I'm sure there was a reason.

**Comment by skddc** [comment]
Compat maybe?

**Comment by jorinvo** [comment]
I played around with this and found out that the problem is, we want not just the textarea to scroll, but also all the menu stuff at the top.
Because of this the parent element has to be the scrollable element and the textarea cannot scroll. The height of the textarea has to grow with its content.
And this is not possible with only css right now (see http://stackoverflow.com/questions/995168/textarea-to-resize-based-on-content-length, https://css-tricks.com/textarea-tricks/, http://stackoverflow.com/questions/2803880/is-there-a-way-to-get-a-textarea-to-stretch-to-fit-its-content-without-using-php).

I guess, we just keep autosize for now.
