### ISSUE TITLE
Fix remotestorage documents module

### ISSUE THREAD

**Issue by jorinvo** [litewrite/litewrite#234]
Remove using `.extend()`, `.scope()`, and `.cache()`.
Use clients directly.

**Comment by skddc** [comment]
`scope()` is actually fine for scoping a client by path.

**Comment by jorinvo** [comment]
@skddc so is the problem with the `.extend( )` maybe?

**Comment by skddc** [comment]
We moved the util functions at some point, so maybe.

**Comment by jorinvo** [comment]
Was no problem with the module.
Still a problem with the dependency system from RS combined with webpack I guess.
See here: 5af22c4899d08e79a893dafab9a5d3c4d65941a5

Really hard to find if the error is hidden by a promise. 
If promises handle errors and it's not the error they handle, they should re-throw them ...

**Comment by skddc** [comment]
Good catch!
