### ISSUE TITLE
Get remote content into litewrite via URL

### ISSUE THREAD

**Issue by jorinvo** [litewrite/litewrite#241]
I think it would be a cool feature for bookmarklets or other web services if they could specify in a link to litewrite what content to open.
The content would open in a new file and not affect any existing documents.

We could use some URL parameter for this.

One way would be to directly accept URI encoded content as for example: 
`litewrite.net?new_document=Some%20Title%0A%0AAnd%20some%20content%0Awith%20lines` to get:

```
Some Title

And some content
with lines
```

**Comment by jancborchardt** [comment]
Yeah, that sounds like a neat idea! :)

**Comment by skddc** [comment]
Someone recently played around with that and called the concept urlhosted. :)

Here's a link to the blog post, with content contained in its URL:

http://urlhosted.graphicore.de/#?eJyFV39v5LYR/Sq8NYLEglfyj97hYhRJnUPu7MDXHGIHRmIVASVxJWYpUiGpXW+KAv0Q/YT9JH0zlHZ9wQX9x97lr5l58+bN7D8XUUejFpeLh05GoYOInQ5fL04Wcoyd89i4lSEo8VaHqPyJiFsd8eFS/M3Q+mpabnXsxgqrrZdDp2vnFd5oZKSnz0/PXi5Pv1yevb4/O798eXZ58So/f/36Z5yonY3KRhzKRm+uHV5rMnJDWpFl6mlQXvc4IE2Wia2qhBwGuAhXex3GoEJpY6fEIH0UcgVXBH19LBdH5eIfX3QxDuGyKJTNt3qtB9VomTvfFvSteOtlS2//ohv81Sut/HFp3UpI8eMPtyI6ESLigCuN8Eo2AuHIvLSlvYcNcgR+Ztlou+R2los7pRhA0QAZq6N2Vqy868XjfIrMHxx7vlocX9LbX4krE5xYW7e1QgZRLoLyG+WNCqFcnOB7bTT8XQa4TQvO05koo67LxYxROBHz2/sl0ThhXRRBIaCdG70AgJ6jomABnPYiGcvFt0goNnFMIEdW1TFdIa/SGYEk+BHA9Yqd4G1+DM7sggBROm05H5V3W1yasAM8vZI2UY1xtCpZY7wDnPTsJLFgJ5AQerq0s6O0OLt5YxGibE7YjNF2nchhnGwCrwUdVWn7MUR4oW0rdPw8cBScTXFPx+njf//9H73CrqhBvUpxxrG21caUFt8bHQYjd8jVPgpO/9vb7+/ucPCtR+5vdQXCfD8oK+7gc63wbxW30qssK+1om4mg2bsPt2JzAcY8Epe8GhwcdX53oEaqqLx2fXGoqWJfJMdcJFG80/EaxxInZ2O0NyV/BSxX5FqjPZJodhMf0z3xQbYqHIwO9DV/ZhoFQfQH5M4qhqZxnLcXhMLRkbh2WywhaUBu6/z6a1q/0/1gVC4eOmXVZqLRRiPEfU6YHiIb5I5ylU3ZnfiC8ksZJXJ4RbCFlFg+JVkeUPK6hpXSkpk/M+HGKCYj4g8mSkt3CK49NgPoh9qioiH36CA0A4nBNYjLStaK038VmYXE/VQi8Ce6tjXqk3dQaKBekqos+xa7ULNqjBHyIJPD0Q3E9CloGPlBtdI3VPVCryYj/QSb3IfElIcp1DVxwIlerlmCbBuEkkGzZtP76gnybgfAQZTgtV5qxDLhmE6EcRicj0E8vpd+3aBO/p+KzudmppB4QQLGKqhIEV3fv79lzD54iiVBcNcB9hcHELbPiFLarbSR5ZdOJV2ZnYTrv1ItJ2Um0mk7yUPl3LqHMwGghJiL7MqYlHJmPBlG5P2JGMzIfpS2Hj3YxaxKMs8JRfFAXrQ0+ndqRhwVJGpbWkYb2zXEgVRbXInKPQmHeg98buJPeCZHjtWjdoOmC393USUms/jR7do49DEidXCOJZ9B6F2jVzt+iII4gSbVEoLNKy3g8uSCmF0CzymKhklmc/HTxErOB5tIdcGQkln5jMLVrrQd+jrp46cTJFtwJZ9q/qHbocwflDEnSU5h59CqIcpC9iBfS2KHLEJ8wODgegUNQXahqCJjntIac5U60Wo0GYWRykCHfQ+qdoid60fbMKBUG6IBVrmqiAP7+iVlEJVBJdIO9DpSyg+KHZ0zoqNThvQdFybL4hGpa1QNijqfKA/GR+ldpUM3K6J2xXeu70aQozgyeqOOCW4geYNaaghd1I4hd2EW+nfDE5VMZgFF4g0gUNVy5YjkKlDDofwjtgje4zYYDc7SdoOaMG4gVEEt9yuCTEpP2TxcZfUhDQTRuDCaWeVkja7RJOxCGIkDPMnMfXlsl9HLek0q8ciFZTTyAtTVJzvR/QTIAQZ+NhQX50f8CYfI2+XZX05ffvny9PT8mMEHEJx2ZiO8ZGVEAEy4RJEtGZ2kqu6srqWhgus1qkkSmFDskNRaBd1aBBn5LQY9Va8Tg8PTSIpD2wjcgTEJ0dCTzkZutmmDGITvfVBmg6bHk0Bpg9SYJm4SDnQcU5YkSga5mcojqMmXSP+XbJ/qsbTI0UZTs8JrrMNpWGbFVU+SmuLJvl/sEw53t0pRhlWMO8wuZAZiDM/nDtZNxh23dXab5HbHoOUiIjmYwZ3LW8O1oWMOIjHk1aSgdPFQwI779PudsDIp3vMpH1MJdmg0l/XUcmmg2JOCOLEfSfJGoTPw5FDwT4Lj2cobuQHdMaEDzsbZzyMPtUJWFNFHiRZTnhn0Xj7pnpJPQ7hRtkXDA1+hhivFah1qhaalXaBQO7yI1KgC8hPIe0r/YRSF39Rb5rIg0fs4aaxWxEr2sLTsIj3KCo4ebGiWGCWP8nht5RKUlA7JY6iuFRE1tV1k/oa7eBrCondjhbZ1k3IBflSyQmYi2IGSBLg0ibKH2jaAgiSdqEwVwV4kIoOh3DUOCUQkygTFabyerEmxJr7Zv1ZeFF+V9sUjHnz2Y2OgkYF7eP9RD+eOXlDpOhsKFHtfFa+KV7K4++zNxWffvIq/rGWMo21V/t2Hd6j10+Fp+cm949n0mzfLb35a3l0tL/JTKrSH2Wj6zXH2m/z9XHxBSmwdwbLShsR08a//AaimNR0=

**Comment by jorinvo** [comment]
Nice idea!
Just bad that browsers have URL length limit (humans probably too).

**Comment by skddc** [comment]
> Just bad that browsers have URL length limit (humans probably too).

No official ones actually. Or did that change since I last checked? :)

**Comment by jorinvo** [comment]
@skddc I just remember when I needed to store data in the URL a couple of years ago and had to support IE.
But I think you are right about modern browsers :)

**Comment by jorinvo** [comment]
Closing this for now. PRs still welcome though.
