### ISSUE TITLE
keeps requesting folders on storage.tuxed.net

### ISSUE THREAD

**Issue by fkooman** [litewrite/litewrite#242]
Is there anyone willing to test litewrite.net with my storage server to debug the issue where litewrite keeps requesting its folders over and over again?

Account: foo@storage.tuxed.net, Password: bar

**Comment by jorinvo** [comment]
@fkooman works fine for me. 
Just tested it in a private tab in Chrome. Refreshed the page a couple of times and typed some text.
What do you mean?

**Comment by fkooman** [comment]
Can you please test in Firefox :) I forgot to mention that, I don't have Chrom(e)(ium) :)

**Comment by fkooman** [comment]
You'll see it in the browser console :) continues requests of folders (ctrl+shift+j)

**Comment by fkooman** [comment]
![screenshot from 2015-11-19 14-36-15](https://cloud.githubusercontent.com/assets/616885/11272126/f2739cf8-8eca-11e5-9662-b1ed24e87f34.png)

**Comment by skddc** [comment]
Those look like normal sync requests. Do they happen more often that every 10 seconds?

**Comment by fkooman** [comment]
Yes, a few times per second.

**Comment by jorinvo** [comment]
@fkooman you tried it with another storage provider?
Does it look different?
And is it only with Litewrite or do you get the same thing with other RS apps?

**Comment by fkooman** [comment]
It works fine with 5apps storage. I can't reproduce it with for example https://myfavoritedrinks.5apps.com/. There is only performs those requests every ~ 10 seconds.

I saw 5apps storage does not return ETag on folder requests, but disabling ETag on my folder responses also didn't help.

**Comment by skddc** [comment]
> I saw 5apps storage does not return ETag on folder requests, but disabling ETag on my folder responses also didn't help.

How would you get 304s on folders then? (Visible in your screenshot.)

**Comment by fkooman** [comment]
Those are with ETag enabled...

**Comment by fkooman** [comment]
litewrite uses /** remotestorage.js 0.10.0-beta, http://remotestorage.io, MIT-licensed **/  does that have anything to do with it possibly?

**Comment by skddc** [comment]
Ah, right. Anyway, we do deliver ETAGs on folders, but omit them for 304s, because they aren't necessary there. You wouldn't get a 304 in the first place, if there hadn't been an ETAG on the original folder request.

**Comment by fkooman** [comment]
Right. Maybe this: https://github.com/remotestorage/remotestorage.js/commit/f5043493de2b8536166d5667c8af8e1b94fecfa5 ?

**Comment by skddc** [comment]
> litewrite uses /** remotestorage.js 0.10.0-beta, http://remotestorage.io, MIT-licensed **/ does that have anything to do with it possibly?

It's most likely some bug in 0.10. Did you follow the recent updates? Litewrite is in the process of getting updated completely, and the new version is available for testing, too:

https://jorin.lepus.uberspace.de/litewrite/

**Comment by fkooman** [comment]
Yes I followed it a bit, but was not clever enough to test it with that version! That version works fine!

So I guess this problem will resolve itself eventually! :)

**Comment by skddc** [comment]
Hooray!

**Comment by jorinvo** [comment]
Ah thank you for figuring that out guy!

We should really update litewrite.net soon to not confuse more people.

I'm pretty busy with work at the moment. But I try to finish the sharing feature soon. 
Then we should be ready to update.
