### ISSUE TITLE
Better deployment flow

### ISSUE THREAD

**Issue by jorinvo** [litewrite/litewrite#244]
The old deployment flow was really manual.
Had to build the project, checkout the version from the server, do a commit and push to the server (server meaning 5apps).

With the new setup `npm run build` creates a working version with only the necessary files at `dist/`.
I'm not sure if this is really needed or if we should just deploy the same way like we do with _gh-pages_ ...

Also it would be nice if we could setup the _master_ branch to with a deploy hook to automatically deploy to litewrite.net.
@skddc any idea if this is possible?

**Comment by skddc** [comment]
> Also it would be nice if we could setup the master branch to with a deploy hook to automatically deploy to litewrite.net.
> @skddc any idea if this is possible?

Hook where? You could do it from a CI server for example.

**Comment by jorinvo** [comment]
@skddc good idea! I was thinking too complicated.
I should check out [Travis](https://travis-ci.org/).

**Comment by skddc** [comment]
Maybe this is a good time to finally write our Travis deployment integration. They have that for Heroku and others. :)

**Comment by skddc** [comment]
If you want to deploy from Travis, this is probably how you'd want to do it: http://docs.travis-ci.com/user/deployment/script/

**Comment by jorinvo** [comment]
Thanks, should be straight forward if we can git push to 5apps from Travis.

**Comment by jorinvo** [comment]
Alright. I setup Travis: https://travis-ci.org/litewrite/litewrite
We have a `master` branch now that should deploy automatically with a `git push`.
I put `REPO_URI` and `DEPLOY_KEY` into env vars. That should be save enough I guess?
Will be testing this when we actually deploy to litewrite.net again.

**Comment by skddc** [comment]
![thumbs-up-cool2](https://cloud.githubusercontent.com/assets/842/11452067/20d0f970-95d2-11e5-832e-aa16033272cb.gif)
