### ISSUE TITLE
Hide sharing button and RS widget

### ISSUE THREAD

**Issue by jorinvo** [litewrite/litewrite#245]
Litewrite should be as clutter-free as possible.
We already hide the sidebar. 
Could we also hide the RS widget and the sharing button?

I tried already to only show them when we set the body.show-aside class. 
But they should also be visible on hover.
Also, we could think about placing them in the sidebar instead.
@jancborchardt what do you think?

**Comment by skddc** [comment]
The new widget is almost done, so I would wait with that, before you have to work on that twice.

**Comment by jorinvo** [comment]
@skddc thanks! Looking forward to it!

**Comment by jancborchardt** [comment]
Yeah, I’d place them in the sidebar on the left bottom, just above our slogan with links.

**Comment by skddc** [comment]
Damn, you're forcing us to implement widget extension to the top then. :) (It's fine.)

**Comment by jorinvo** [comment]
@jancborchardt sharing too?

**Comment by jancborchardt** [comment]
@jorinvo sharing could go next to the modified date on the bottom. Although that would make it a bit cumbersome for long notes. But similar now, except sharing is at the top.

**Comment by jorinvo** [comment]
Sounds good.
