### ISSUE TITLE
Insert spaces when tab key is used

### ISSUE THREAD

**Issue by jorinvo** [litewrite/litewrite#246]
(Note that this is just an idea for the future)

Clicking _tab_ should insert 2 spaces at the cursor position.
Clicking _shift+tab_ should remove 2 spaces at the beginning of the current line.

2 spaces would be useful since it matches the indentation of a bullet list:

```
- I like to use bullet points.
- But some items need multiple lines.
  And the next line needs to be indented  2 spaces.
```

Of course,  an even smarter system would preserve the indentation for the bullet list right away.

**Comment by jancborchardt** [comment]
Yup, I totally agree, good point!
