### ISSUE TITLE
Change welcome doc on mobile

### ISSUE THREAD

**Issue by jorinvo** [litewrite/litewrite#253]
https://marketplace.firefox.com/app/litewrite/ratings/655866

Maybe we could remove the shortcuts part on mobile to give users a more optimized feeling.
@jancborchardt any ideas how to improve this?

**Comment by jancborchardt** [comment]
True, it’s not needed on mobile. Can we check via JS if a physical keyboard is present? Or should we do it via screen resolution?

**Comment by skddc** [comment]
You could check for touch.

**Comment by jorinvo** [comment]
should go for touch. also, this doesn't mean we need to disable the keys. we just don't show the message.

**Comment by skddc** [comment]
Might want to show it on an iPad Pro though. ;)

**Comment by jorinvo** [comment]
I would suggest that we don't try to show different text on different platforms.
It should be good enough to change the welcome doc to make it more obvious that the shortcuts only work with a proper keyboard (in theory you could also connect a keyboard to your tablet...).
