### ISSUE TITLE
Offline throws syncing error

### ISSUE THREAD

**Issue by jorinvo** [litewrite/litewrite#259]
Thanks to appcache the app works offline. 
But if you are signed in the app doesn't work.

remoteStorage fails syncing and this seems to break the whole application...
Unfortunately the error trace isn't that helpful either. 
But I would guess it's another issue with the module system of remoteStorage...

Anyone has an idea for this or saw this before?

![syncerr](https://cloud.githubusercontent.com/assets/738978/12007024/68f5db00-ac23-11e5-8a5d-8f7cb9454ba0.png)
![rsjs](https://cloud.githubusercontent.com/assets/738978/12007025/6cb19c48-ac23-11e5-8d9f-ba5e1de53761.png)

cc @skddc

**Comment by skddc** [comment]
What's "the module system of remoteStorage"? It does look like the library is not loaded properly.

**Comment by skddc** [comment]
... btw, there's definitely an open issue with starting rs.js apps while offline. See https://github.com/remotestorage/remotestorage.js/issues/869

We need more feedback and help to solve it. /cc @galfert

**Comment by jorinvo** [comment]
Sorry, by module system, I mean the way RS puts its internal files together. It seems like it's not using any of the standard tools.
And it's not really compatible with webpack (as used by litewrite).
I fixed multiple places in the version of RS we use in litewrite.
It's always an issue that some dependency cannot be found.
(For example this one: https://github.com/litewrite/litewrite/commit/5af22c4899d08e79a893dafab9a5d3c4d65941a5)

**Comment by skddc** [comment]
Oh you mean the dependencies in global variables. Got it. The whole internal loading/module system definitely needs some good refactoring.

**Comment by jorinvo** [comment]
Since this is remoteStorage related, I removed the important `priority` label for now.

I think this doesn't stop us from publishing this version to litewrite.net since the existing version there doesn't have less remoteStorage bugs.

**Comment by skddc** [comment]
Ship it!

![ship-all-the-ships](https://cloud.githubusercontent.com/assets/842/12392816/dabe1c7c-bdbf-11e5-841d-09ae4354ef97.jpeg)

**Comment by jorinvo** [comment]
Should be fixed with rs, not here.
See https://github.com/remotestorage/remotestorage.js/issues/945 for more.
