### ISSUE TITLE
Update litewrite.net

### ISSUE THREAD

**Issue by jorinvo** [litewrite/litewrite#262]
After this translation is done #260, I would like to deploy to litewrite.net.
@jancborchardt what do you think?

**Comment by jancborchardt** [comment]
Yeah, sounds good! :)

**Comment by khertan** [comment]
euh ..... Did you change http to https ?
Look like it s store in different backend in cozy remotestorage server ...

**Comment by jancborchardt** [comment]
Sounds like http/https should be handled the same by Cozy/remoteStorage? cc @skddc

**Comment by skddc** [comment]
It's technically a different origin. Sorry, forgot about that when adding HTTPS without asking.

It would be possible for a server to handle this as the same app, but security folks might say it's not prudent.

**Comment by khertan** [comment]
i agree :) it s not prudent.

So if other have such issue, i just copy the indexeddb in the mozilla profile from http://litewrite.net to https://litewrite.net ...

And patch my cordova android apps :)
Thanks

**Comment by jorinvo** [comment]
https://litewrite.net/ is updated!
Check it out! Give feedback. Open issues :)

**Comment by skddc** [comment]
It seems I had some things cached still which broke the app and showed a blank page. Hard-refresh helped. (FYI in case someone else runs into it).

**Comment by jorinvo** [comment]
@skddc thanks, I keep it in mind if someone has trouble.
