### ISSUE TITLE
How do I sync with dropbox?

### ISSUE THREAD

**Issue by qbektrix** [litewrite/litewrite#266]
I am sorry if this is a weird question but how do I sync with dropbox? I was unable to sync on the version at litewrite.net.

**Comment by jorinvo** [comment]
Hi @qbektrix! It's not a weird question.
Remotestorage was supposed to support Dropbox, but plans changed and it's not supported at the moment.
I have to disappoint you. You can't use Litewrite with Dropbox at the moment.
If you still would like to give it a try, the easiest Remotestorage provider to sign-up for currently is [5apps](https://5apps.com/).

- [ ] Remove Dropbox and Google Drive support from README

**Comment by qbektrix** [comment]
What are my options for syncing with a cloud solution that I do not host(like dropbox or skydrive or G Drive)?

**Comment by jorinvo** [comment]
@qbektrix I'm sorry, for now we can't support these platforms with Litewrite.
There are enough other note-taking apps you could try that are specific to one of those platforms :)

**Comment by skddc** [comment]
Just FYI: Dropbox and Google Drive support are coming to remoteStorage.js sometime this year. You can track (and/or contribute to) the development of the new connect widget here: https://github.com/remotestorage/remotestorage-widget
