### ISSUE TITLE
Switch to using ServiceWorker instead of AppCache

### ISSUE THREAD

**Issue by michielbdejong** [litewrite/litewrite#267]
Open https://litewrite.net in Firefox 44+, open the devtools console, and refresh the page. You'll see a warning:

> The Application Cache API (AppCache) is deprecated and will be removed at a future date.  Please consider using ServiceWorker for offline support.

**Comment by michielbdejong** [comment]
One easy way to generate a ServiceWorker is https://github.com/mozilla/oghliner

**Comment by jorinvo** [comment]
Thanks @michielbdejong! Will look into this at some point :)

**Comment by skddc** [comment]
... also, please don't do it *instead* of AppCache. SW are not stable yet, and only implemented in two browsers at this point. And there's really no reason to ever discard offline support for today's current phones and such anytime soon.

**Comment by jorinvo** [comment]
Good point!

**Comment by raucao** [comment]
I made it in April 2016 though. :)

Currently, AppCache still works, but Chrome will currently only accept a running SW as a signal for "appiness", which will trigger the install dialog on repeated usage. However, when you have AppCache enabled, and it finds a SW, no matter if the SW is caching all files, the AppCache process will be disabled.

Google is basically driving a hard marketing campaign for SW, and making our lives harder in the process. We're still deciding how to handle this best for automatic offline caching on 5apps Deploy, but for Chrome there's currently no alternative but to re-implement AppCache on top of SW.
