### ISSUE TITLE
Unable to connect to my Google Drive

### ISSUE THREAD

**Issue by andhrizz** [litewrite/litewrite#270]
I am able to use it in different browsers comfortably but when I have added my Google Drive by giving email address it is not synchronizing. Am I missing something I need to do ?

**Comment by skddc** [comment]
Are you using the version published on https://litewrite.net?

**Comment by jorinvo** [comment]
Sorry, we can't help with Google Drive at the moment.
To find out (or contribute) to the progress best talk with the remotestorage community here https://community.remotestorage.io/

**Comment by andhrizz** [comment]
I am using the version published on [Litewrite](https://litewrite.net/)

**Comment by skddc** [comment]
The data sync library used in Litewrite has experimental support for Google Drive. That's why I asked.
