### ISSUE TITLE
Alt-j doesn't do anything

### ISSUE THREAD

**Issue by theWebalyst** [litewrite/litewrite#272]
Tried locally and http://litewrite.net in Firefox and Chromium (Linux LMDE). Alt-n up/down arrow all work.

What is Alt-j supposed to do?

**Comment by jorinvo** [comment]
Hi @theWebalyst! 
`alt-j` (focusing the search) only works when the search is available.
Currently the search is only available if you have more documents in the sidebar than fit on the screen.
You can try it out by adding a few documents or by resizing your browser.
Then the shortcut should also work.

This behavior can be a little bit confusing and we would be happy about suggestions for improvement.

**Comment by theWebalyst** [comment]
Ah, thanks.

I'd suggest updating the help document to say "Alt-j - search document names (inactive when all document names are visible)"

Search to me implies searching document content. If as you suggest it doesn't, that isn't clear. If it does search content, then it makes no sense to disable it if the names are visible.

**Comment by jorinvo** [comment]
Good idea! 
I added an issue for this: #273
