### ISSUE TITLE
Screen blink when I type at the bottom.

### ISSUE THREAD

**Issue by githubtefo** [litewrite/litewrite#276]
Hi!
When the writing reach the bottom of the screen, every time I type the screen blink. It's very annoyance to write at that point.
Anyone else experiment this behaviour?
Thanks!

**Comment by jorinvo** [comment]
@githubtefo yes, I can see what you you mean. 
Unfortunately I don't have time to work on Litewrite lately.
But if you or anyone else would like to send a pull request I would be happy to merge it :)

**Comment by jorinvo** [comment]
@githubtefo I finally got around to make some updates on Litewrite. I can't reproduce the issue anymore. Would you mind checking if you still get this behavior? (Also make sure your browser cache is cleared) 
Thank you!

**Comment by raucao** [comment]
Fantastic! I don't get it anymore and it's SO much better now. :)

**Comment by githubtefo** [comment]
Perfect! Thanks!
Solved.
