### ISSUE TITLE
Update intro text

### ISSUE THREAD

**Issue by jorinvo** [litewrite/litewrite#279]
As @skddc mentioned [here](https://github.com/litewrite/litewrite/issues/278#issuecomment-304510113), the text needs to be more clear about how document are stored.
> The text should probably be adapted a little bit, because I think it wrongly suggests that brower storage is safe long-term, when really you should sync your stuff to a remote server:
    > It works offline and your browser will keep your data saved (nerd facts: AppCache & localStorage).

**Comment by jorinvo** [comment]
Changed it in https://github.com/litewrite/litewrite/commit/a1ad34be2ed9e1da8c12be97d7ee316a41e75da2.

**Comment by skddc** [comment]
![thumbs-up-cool2](https://user-images.githubusercontent.com/842/28932845-32ddb030-787b-11e7-9541-a9536493cf1f.gif)
