### ISSUE TITLE
Upgrade to rs 1.0

### ISSUE THREAD

**Issue by jorinvo** [litewrite/litewrite#280]
As @skddc mentioned [here](https://github.com/litewrite/litewrite/issues/278#issuecomment-304510113), upgrading to the latest remotestorage version would enable users to sync to Dropbox and Google Drive.
> By the way, we're already testing out rs.js 1.0 in actual apps (currently finishing up work on the new widget lib), and with that you can also easily connect Dropbox and Google Drive in addition to RemoteStorage accounts. I'll gladly help with upgrading this app.

**Comment by jorinvo** [comment]
@skddc any updates on rs 1.0?

**Comment by skddc** [comment]
Yes, we're almost ready for the release candidate. Probably happening during SHA2017 this weekend, or the week after. I'll add documentation for porting modules and all. But you can also look at how they're built now by checking out already-ported ones, like e.g. [bookmarks](https://github.com/lesion/remotestorage-module-bookmarks) or [chat-messages](https://github.com/67P/remotestorage-module-chat-message) for example.

**Comment by jorinvo** [comment]
Thanks, will update when it's released then :)

**Comment by raucao** [comment]
Sorry, that took a while, but we just spent literally most of October working on rs.js, so it's going to be a great release!

Here's a guide for upgrading apps: https://community.remotestorage.io/t/how-to-upgrade-to-rs-js-1-0-from-0-14-or-earlier/413

We'd be happy if as many people as possible tried out the latest release candidates of both [rs.js](https://www.npmjs.com/package/remotestoragejs) and the [connect widget](https://www.npmjs.com/package/remotestorage-widget) add-on. These look like they'll become the final `1.0.0` versions.

**Comment by raucao** [comment]
1.0.0 is finally released: https://community.remotestorage.io/t/remotestorage-js-1-0-0-released/414

**Comment by jorinvo** [comment]
This is huge! Looking forward to adding support for this! The new widget looks great!
Dropbox and Google Drive support is amazing!
Also we can require remoteStorage using npm now instead of keeping our own version in `lib/`.
@skddc should I move the [remotestorage-documents](https://github.com/litewrite/litewrite/blob/gh-pages/lib/remotestorage-documents.js) to a separate npm module now? Or is there an existing module?

**Comment by raucao** [comment]
> @skddc should I move the remotestorage-documents to a separate npm module now? Or is there an existing module?

Yes, definitely!

If you do, you could check out the shares module for how to add JSDoc comments and automatically build them into the README for module documentation: https://github.com/skddc/remotestorage-module-shares

**Comment by jorinvo** [comment]
Litewrite is now using the latest RemoteStorage.
The documents module moved to https://github.com/litewrite/remotestorage-module-documents.
Checkout https://litewrite.net and try out the new Dropbox and Google Drive integrations!

**Comment by raucao** [comment]
![rejoicing](https://user-images.githubusercontent.com/842/32503417-6a839d4e-c3dd-11e7-8d7b-fb6dfd831f9e.gif)
