### ISSUE TITLE
opens new tab instead of navigating to existing open tab on Chrome

### ISSUE THREAD

**Issue by RichGriese** [litewrite/litewrite#281]
Hey there, just found you app. Looks really sweet. One thing. If I pin the app to the app to the Chrome shelf, and click it to open... it opens. But... if I click the icon again, it opens again in another tab. It seems to me it should navigate to the open tab. The app Write Space (Don't think it's on the chrome store anymore, but I'm still running a copy) will navigate back to the open tab. Would be nice if you could stop it from opening itself in multiple tabs.

Cheers!

**Comment by jorinvo** [comment]
Hi. I'm afraid we can't affect the behavior of Chrome here. I can imagine that this is because we reference the current document in the url#hash and Chrome treats it as a different page then. Unfortunately this is not something we intend to change.
