### ISSUE TITLE
Sync / backup to Google Drive?

### ISSUE THREAD

**Issue by RichGriese** [litewrite/litewrite#282]
I'm loving Litewrite. I have 2 Chromebooks & would like a way to sync the data sets on them. Is there even a simple way to export the data to Google Drive so that I could then import it from the other? I don't need an actual sync where I am working on both chromebooks as the same time, just a way to transfer the data from one to the other.

Cheers!

**Comment by RichGriese** [comment]
BTW... scratch that request. When I started using Litewrite a few months ago I an uBlocked the "connect remote store" items... I just remembered I did that, and now an looking at the https://remotestorage.io/ page it links to. Cheers!

**Comment by jorinvo** [comment]
So it is working now? Then I'm closing this issue. Glad to hear you like it!
