### ISSUE TITLE
Can't select/copy/paste on iOS anymore

### ISSUE THREAD

**Issue by raucao** [litewrite/litewrite#286]
Not sure what changed, but when I tried using Litewrite on iOS after a while just now, I couldn't select/copy/paste anything. It would show the keyboard, but remove the cursor every time.

**Comment by jorinvo** [comment]
Had the same issue on Android. Let's see if it is any better now.

**Comment by raucao** [comment]
Ok, cool. Regarding your commit comment about the widget, you can actually make it less wide if you want to. Shouldn't cause any issues. Another option would be to move it elsewhere, or to only open it on click/tap.

**Comment by jorinvo** [comment]
Good idea @skddc. I added some margin. The menu button should be clickable now.
