### ISSUE TITLE
Excessive dropbox permission grant

### ISSUE THREAD

**Issue by hauau** [litewrite/litewrite#287]
Litewrite requesting access grant to all my files and folders when trying to use Dropbox storage option. There's absolutely no need for that grant. It should use proper api for separate app folder.

**Comment by raucao** [comment]
There *is* actually a need for that grant, and that's to ensure you're not locked into a single developer's app, but that other apps that you permit, can also access and edit the same data. Unfortunately, Dropbox doesn't allow different apps to access the same app folder, and it doesn't have any other permission model to support that.

It would be great if Dropbox would introduce better permissions to prevent Web-2.0-style per-app data silos.

**Comment by hauau** [comment]
I think I am missing something. Does litewrite need to access data produced by other applications? If no then it can live in its own folder. If there is an application that needs to access notes produced by litewrite then I will grant such access to such application. 

Perhaps every remoteStorage application share same dropbox grant or there's some other rs limitation? Then it would make sense for me. Otherwise every app should have only required access and not more than that. Sorry, probably missing something obvious :\

**Comment by raucao** [comment]
> If there is an application that needs to access notes produced by litewrite then I will grant such access to such application.

That's what I tried to explain: it's not possible for applications to access other applications' app folders. It's a limitation of the Dropbox API.

> Perhaps every remoteStorage application share same dropbox grant or there's some other rs limitation?

Yes, that's exactly the case. It's to ensure that any new applications in the ecosystem can access the data of any other application, as long as the user grants them access. Unfortunately, with Dropbox this means granting access to all files (which you can of course check that it doesn't happen), while with remoteStorage you only ever grant access to a specific category of data, like e.g. documents/notes in this case.

**Comment by hauau** [comment]
You are right, that's a problem. I didn't know about this unfortunate dropbox limitation. Thanks for explaining <3

**Comment by raucao** [comment]
Sure, you're welcome! It's certainly neither intuitive nor ideal. Thanks for asking here, instead of just ranting to strangers on the Internet. :)

**Comment by jorinvo** [comment]
hey @hauau @skddc, I do actually agree with @hauau here. 
It would be nice if Dropbox has something like folder level permissions, but they don't. It's not made for the same use case as remotestorage.
I have hard times leaving the permission as they are right now. I trust you folks working on remotestorage, but I don't expect anyone who is using litewrite to trust us with all their Dropbox content. And I don't want to be at fault if some bug suddenly deletes all of a users Dropbox content.

I think I gonna change the Dropbox permissions back to a single folder. If someone really wants to share content between multiple remotestorage apps, they can create a remotestorage account instead.

**Comment by raucao** [comment]
I don't understand. @hauau seemed to agree with the permissions after I explained the reasons. It would really be a shame if Litewrite started locking in user data, because it closes the door for any other app authors to hook into it imo.

**Comment by jorinvo** [comment]
Dropbox sets these limitations. Users are free to use other storage such as a remotestorage server.
Another way to work around this would be to to use multiple remotestorage apps with the same Dropbox app folder.

I get the idea of sharing data. The reality, though, is that there are not that many remotestorage apps out there that work with documents like litewrite (are there any others). There is not really any use of this potential sharing at the moment.
And I am sure you understand, that as the creator of a remotestorage application one really doesn't want to be responsible for all of a user's Dropbox data.

**Comment by hauau** [comment]
I don't agree with full-access permissions but I understand tradeoff that is made by litewrite+dropbox+rs and reasons behind it as you explained. What is more important - the possibility of a siloed dropbox rs target or risks associated with full access grant to dropbox? That's up to project leadership. That's a tradeoff either in favour of litewrite (note taking app shouldn't have this grant) or in favour of rs ecosystem (interoperability of rs apps and shared common storage)

Personally I'm pleased to hear @jorinvo acknowledges associated risks. Interoperability still available through remoteStorage or reusage of app folder and litewrite still can sync with dropbox.

**Comment by jorinvo** [comment]
@skddc I think we should do what's best for the users as of today. 
If any remotestorage-enabled applications get more popular in the future, that is the point where users will look into using remotestorage as storage and see the benefits of sharing data.
But until there actually is an ecosystem of remotestorage application that make use of the sharing capabilities, there is not a good argument to open up for this risk.

I would be happy to find a way to enable both, but if I have to choose, I would opt for safety of user data.

**Comment by raucao** [comment]
> Dropbox sets these limitations. Users are free to use other storage such as a remotestorage server.

There is currently no tool to migrate data from Dropbox to RS for apps, and a user who doesn't know RS and decides to connect Dropbox first, then learns about RS later, would have no chance of easily migrating their notes right now. So in effect, they stay locked in to Litewrite, because no other RS app can access the data via RS.

> There is not really any use of this potential sharing at the moment.

If we lock in the data, then there *cannot* be any other apps accessing it, so you what you're proposing actively *prevents* anyone from creating or adapting an app to use the same data. We had a lot of work to do on the basics, and haven't gotten to widespread module sharing yet. But that's immediately next on the agenda for rs.js, now that we have the big 1.0 out of the door.

> That's a tradeoff either in favour of litewrite (note taking app shouldn't have this grant) or in favour of rs ecosystem (interoperability of rs apps and shared common storage)

Exactly. Not my choice to make, but I find it sad, when people act in favor of their own project and thereby prevent an ecosystem of interoperable projects to develop. If it were my choice, I would at least give users a way to migrate their data before locking it in.

**Comment by raucao** [comment]
> I would be happy to find a way to enable both, but if I have to choose, I would opt for safety of user data.

Then maybe let's think about how we could enable both?

**Comment by jorinvo** [comment]
> Then maybe let's think about how we could enable both?

How about creating a generic Dropbox App like "Remotestorage Documents", which has folder-based permissions. Then every new remotestorage App that also wants to store documents, just uses the same app?

Edit: Doesn't even have to be Documents specific, can be one for all Remotestorage data. Just don't let Remotestorage mess around with the rest of my Dropbox data.

**Comment by raucao** [comment]
Whoever creates this app would have to manage redirect URIs for any other app, and would thus also be a gatekeeper. So that's not really viable.

I'm more thinking about creating two apps with the two different grants, and setting the app keys on the fly according to user choice.

**Comment by raucao** [comment]
There would actually also be an upside to locking in the data to apps in Dropbox: it makes RS more attractive to use than Dropbox. Maybe that's a good thing.

Edit: so maybe it makes more sense to invest time in migration possibilities than in hacking around Dropbox limitations.

**Comment by jorinvo** [comment]
Hm, true redirect URIs are a problem.

> I'm more thinking about creating two apps with the two different grants, and setting the app keys on the fly according to user choice.

That way you would still need to build some sort of tool to migrate data later on. Right now no one would opt for full access since there is no other app to share the remotestorage documents with. So only later as users find other apps, they would want to share access.
At that point it would be just as easy to let them migrate to remotestorage all the way instead.

I think it's ok to limit the Dropbox storage capabilities. Maybe the widget could mention this somehow..

**Comment by hauau** [comment]
Is there a reason for rs not using common rs app folder in the first place?

**Comment by jorinvo** [comment]
> Is there a reason for rs not using common rs app folder in the first place?

this:

> Whoever creates this app would have to manage redirect URIs for any other app, and would thus also be a gatekeeper. So that's not really viable.

**Comment by hauau** [comment]
Users can issue their own API keys. That's how laverna.cc handles dropbox sync. But that's not user friendly ofc.

**Comment by jorinvo** [comment]
There is another issue with switching the permissions back to a single folder:
Right now there are already 37 Dropbox Litewrite users and we would take their access to their documents when deleting the Dropbox app and creating a new one. I don't want to do that either.

**Comment by jorinvo** [comment]
We have more than 50 Dropbox users now and Dropbox already granted the application. Let's gonna leave it as it is. Litewrite is open source after all and whoever is not ok with something can change things as they like :)

![screen shot 2018-01-24 at 07 40 31](https://user-images.githubusercontent.com/738978/35318125-4e713014-00da-11e8-9435-8f98b7f61d45.png)


On another note, Google Drive doesn't give us much love:

![screen shot 2018-01-22 at 07 28 51](https://user-images.githubusercontent.com/738978/35318167-75143c02-00da-11e8-8194-0be8ed02f070.png)

**Comment by raucao** [comment]
Sounds like you need to go through some kind of developer verification process to disable that warning.
