### ISSUE TITLE
Highlight searched Words/Characters

### ISSUE THREAD

**Issue by technoknol** [litewrite/litewrite#288]
When searching it should highlight words or text with in title or body. 

I've seen that it's using textarea so it's impossible to put span there and highlight. 
But I think plugin like this (http://garysieling.github.io/jquery-highlighttextarea/) will work.

**Comment by jorinvo** [comment]
For now we tried to keep it as simple as possible. Not sure if we really need this. 
If anyone comes up with a non-intrusive implementation, feel free to open a pull request and we can add it.

**Comment by technoknol** [comment]
Thanks for clarification. I'll try to integrate it if I get little bit of spare time.

**Comment by jorinvo** [comment]
Thank you @technoknol!
