### ISSUE TITLE
Impossible to select text on mobile

### ISSUE THREAD

**Issue by michallepicki** [litewrite/litewrite#291]
It seems that long press does trigger a word selection but immediately after I take away my finger the text selection disappears. This does not happen on other websites.

Browser version: Firefox 60.0a1 but I remember this happening on previous versions too.
Android version: Nougat 7.1.2 LineageOS
Keyboard version: Android keyboard (AOSP) 7.1.2

**Comment by raucao** [comment]
I have similar issues, both on Android and iOS. I can't even paste text anymore, as the copy&paste menu just immediately disappears after opening.

**Comment by ruedigerkupper** [comment]
I confirm all of these problems, and this is on Ubuntu Touch. So it is definitely not browser or platform related but appears to be the same problem across all browsers and platforms.

**Comment by jorinvo** [comment]
Would be awesome if someone that actually uses Litewrite and experiences this problem could have a look at this :)

**Comment by clnhlzmn** [comment]
I use Litewrite, am experiencing this problem, and would love to help, but I have no idea where to start. Any pointers?

**Comment by raucao** [comment]
I'd probably try to disable cursor position sync to see if it's connected to that. I think it saves that position somewhere and tries to put the cursor back in the same spot, maybe even across devices. I could be wrong, though. Haven't really looked into the code.

**Comment by clnhlzmn** [comment]
Thanks, I'll look into that.

**Comment by prashantsengar** [comment]
I think that this issue has been resolved but nobody closed it as I am able to select the text on mobile.

**Comment by raucao** [comment]
> I think that this issue has been resolved but nobody closed it as I am able to select the text on mobile.

Same here.

**Comment by michallepicki** [comment]
This was specifically on Firefox on Android. I don't use it anymore but I will install it, test and potentially close the issue.

**Comment by michallepicki** [comment]
There are still issues on Firefox on Android. Long-pressing the text doesn't select a single word. Instead, only the cursor gets inserted.

It is possible to often "Select All" and then narrow down the selection but it's not convenient.

I'll leave this open because of that issue but feel free to close if you don't plan on investing in Firefox on Android support.

**Comment by michallepicki** [comment]
Scratch that, I just tried again and it worked fine. Closing!
