### ISSUE TITLE
remote storage - access token may be compromised

### ISSUE THREAD

**Issue by muralikodali** [litewrite/litewrite#296]
when i tried to connect with remote strorage, following notice is issued by php-remote-storage :

**NOTE: the application does not use TLS, if you continue the access token may be compromised!** 

An application wants to access your remoteStorage data.
Application	http://localhost:8000
Permissions	documents:rw

**Comment by raucao** [comment]
It is simply warning you that you're not using a secure connection, thus the server cannot guarantee the safety of the access token. You can ignore that message if you intentionally run it without TLS on localhost.

**Comment by brianpeiris** [comment]
I assume this was resolved at some point? Trying to access litewrite.net with HTTP redirects to HTTPS and the cert is valid.

**Comment by raucao** [comment]
The OP was running a server without HTTPS on his local computer. There's no issue whatsoever with tokens being compromised.

@jorinvo Could you close this issue please?
