### ISSUE TITLE
Textarea continually loses focus when sidebar is hidden

### ISSUE THREAD

**Issue by brianpeiris** [litewrite/litewrite#298]
Steps to repro:

1. Resize your window's width until litewrite hides its sidebar (you'll see the hamburger menu in the top left)
2. Create a new note, write something in it
3. Create another note
4. Switch back to the first note
5. Now you can't type anything because the textarea keeps losing focus

**Comment by jorinvo** [comment]
thanks for reporting @brianpeiris
