### ISSUE TITLE
remote fonts in litewrite

### ISSUE THREAD

**Issue by ghost** [litewrite/litewrite#314]
Hi everyone.

What do you all think of remote sources?

[litewrite/litewrite/tree/gh-pages/style](https://github.com/litewrite/litewrite/tree/gh-pages/style)

**Comment by raucao** [comment]
Why would you want to serve static assets from somewhere else? There's not that much to gain in regards to performance, especially for someone using the app regularly and thus having the fonts cached anyway.

**Comment by ghost** [comment]
Hi raucao.

> Why would you want to serve static assets from somewhere else? There's not that much to gain in regards to performance, especially for someone using the app regularly and thus having the fonts cached anyway.

thank you for feedback. I will close this issue, you clarified all my doubts.
