### ISSUE TITLE
spread the word

### ISSUE THREAD

**Issue by jancborchardt** [litewrite/litewrite#37]
Once we have it in a reasonably stable and done state, we should put it on https://en.wikipedia.org/wiki/Full-screen_writing_program

Also search other distraction free writers ([LightWrite](http://gun.io/w), [Typerighter](https://typerighter.com/)) and mail their developers, as well as search for distraction-free writer articles and mail their authors.

**Comment by jorinvo** [comment]
Words have spread enough over the last few years I guess.
