### ISSUE TITLE
animation for moving documents in the list when edited

### ISSUE THREAD

**Issue by jancborchardt** [litewrite/litewrite#57]
(the rest of #24)

When editing a document which is not first in list, the documents just switch places without you noticing. There should be a subtle animation which moves the just edited document from its place up top. Also moves the elements above it one element down to make room in the first spot and also to close the now empty spot below. And maybe the elements moving down should be colored a bit lighter for the time of the animation.

**Comment by jorinvo** [comment]
Let's keep it as simple and basic as it is.
