### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by silverbucket** [litewrite/litewrite#95]
Hey, the tag module I've been working on is pretty much ready for use. I was wondering if litewrite could have a tagging system built in? A note taking app I've been using extensively for the past couple years is called 'catch' (catch.com). 

The editor itself is nothing special, but it has a few cool features. The thing I use the most is inline tagging.

So I could do something like
# movies

The Big Lebowski

That would tag that note with the 'movies' tag, and I could later sort by 'movies' and see all my notes with that tag. it's extremely useful when you need to jot down a quick note for later. ie. movie or book recommendations, etc.

Much easier than having to look for your 'movie suggestion' document in your list in order to add a movie to it.

**Comment by jorinvo** [comment]
Closing this for now. If the remotestorage ecosystem progresses in the future and there are actual use cases for this, I'm happy to merge a PR from someone.
